### PR TITLE
Member Profile Update

### LINKED ISSUE #128: Member Profile Update- UI Error
> heyy! just noticed a slight ui inconvenience. also when i tried saving the primary/secondary skills, i got an error and it kept loading indefinitely. x is not a function or something similar. however, the values got saved succesfully - checked on reload

Screenshot_2024-04-16_at_19 43 25
Screenshot_2024-04-16_at_19 39 57

### PR DESCRIPTION
**Pull request by vidvidvid**
Closes #128

| Before | After |
|:------:|:-----:|
|  Screenshot 2024-08-21 at 09 49 55 | Screenshot 2024-08-21 at 09 49 17 |

### CODE REVIEW

**Comment by wtfsayo** [comment]
Can you attach screenshot of change you made?

**Comment by vidvidvid** [comment]
@wtfsayo done

**Comment by wtfsayo** [comment]
> @wtfsayo done

is the profile card scrollable tho. in case somebody has even longer description? Might wanna use how we handle show more on raid-page!!!

**Comment by vidvidvid** [comment]
i adjusted the Description component and reused it for this card as well. reverted to defined height of the card.
https://github.com/user-attachments/assets/469e1110-c7f7-4b59-87cb-345d67351aec

**Comment by wtfsayo** [comment]
so fucking cool!!

**Review by scottrepreneur — APPROVED** [review]

**Pull request merged**
